### ISSUE TITLE
Too much data - 26 MB

### ISSUE THREAD

**Issue by gstroup** [PredixDev/px-demo-data#1]
## Expected behavior and actual behavior:
I'd like to speed up bower install.  Can we remove some of the sample data from this package?  Perhaps remove it as a dependency from some other chart components?

## Steps to reproduce the problem:
Install this repo with bower, or install a component that depends on it.  For instance:
bower install px-vis-timeseries
(or px-chart or px-vis-xy-chart)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v 0.0.20

## Code examples 

[14:25:12]212427954:predix-seed> pwd
/Users/212427954/code/githubcom/predixDev/predix-seed
[14:28:39]212427954:predix-seed> du -sh public/bower_components/px-demo-data/
 26M	public/bower_components/px-demo-data/

**Comment by nonmetalhail** [comment]
The datasets are necessary for testing various charts under large datasets and are used in the demos. They should only be imported as a devDependancy and therefor wont slow down production. I see that timeseries does have it in the wrong place, so I'll move it there. The vast majority of the 26MB comes from one file, which we do need.
