### ISSUE TITLE
Can we bump to 1.x.x?

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-demo-data#2]
Can we bump this to a 1.x release so we don't get bower weirdness? Not sure off the top of my head which repos used this, I just got a weird resolution warning in the predix-ui.com site repo. (guessing @benoitjchevalier @nonmetalhail of most interest 👍 )

**Comment by benoitjchevalier** [comment]
I think it's mostly used in vis charts. I don't see any issue bumping it to 1.X.X, it's only used as a devdependency for our components, just need to update those components

**Comment by katemenkhaus** [comment]
It is causing this version clash. 
![screen shot 2017-10-16 at 9 10 21 am](https://user-images.githubusercontent.com/14931112/31622704-01c58bb0-b252-11e7-9b55-4017786e686b.png)

**Comment by benoitjchevalier** [comment]
we could change the predix-ui resolution to be `~` instead of `^`, that would work for now and avoid bumping all the vis repos

**Comment by mdwragg** [comment]
I bumped it to 22 but didn’t push the code last night.

**Comment by mdwragg** [comment]
(Which fixes it)

**Comment by mdwragg** [comment]
Prob easiest if we just switch it to 1.x so we don’t run into it again?

**Comment by benoitjchevalier** [comment]
up to you, `~` will pick the latest patch which should prevent it from re-happening. Or bump all repos using it

**Comment by nonmetalhail** [comment]
I'm bumping to 1.0.0 and will update the vis charts. I do not see predix-ui requesting it in its bower.json. So @katemenkhaus is responsible for updating whatever that version clash is.
